diff --git a/Makefile b/Makefile
index 716d9e2..0f10600 100644
--- a/Makefile
+++ b/Makefile
@@ -25,10 +25,9 @@ modcutest-config:
 
 #   install the shared object file into Apache 
 install: modcutest-config install-modules-yes
-	install -d $(modcutest_includedir) $(modcutest_bindir)
-	cp ModCuTest.h $(modcutest_includedir)/ModCuTest.h
-	install -D modcutest-config $(modcutest_bindir)
-	ldconfig
+	install -d $(DESTDIR)$(includedir) $(DESTDIR)$(bindir)
+	cp ModCuTest.h $(DESTDIR)$(includedir)/ModCuTest.h
+	install -D modcutest-config $(DESTDIR)$(bindir)
 
 uninstall:
 	rm -f $(modcutest_includedir)/ModCuTest.h
